Build(deps): Bump the nav-deps group across 1 directory with 11 updates (#988)
Bumps the nav-deps group with 11 updates in the / directory:

| Package | From | To |
| --- | --- | --- |
|
[no.nav.ung.deltakelseopplyser:kontrakt](https://github.com/spring-projects/spring-boot)
| `2.7.0` | `2.9.0` |
| [no.nav.k9.felles:k9-felles-root](https://github.com/navikt/k9-felles)
| `9.2.9` | `9.3.3` |
|
[no.nav.k9.felles.sikkerhet:k9-felles-sikkerhet](https://github.com/navikt/k9-felles)
| `9.2.9` | `9.3.3` |
|
[no.nav.k9.felles.oidc-token:k9-sikkerhet-azure-cc](https://github.com/navikt/k9-felles)
| `9.2.9` | `9.3.3` |
|
[no.nav.k9.felles.integrasjon:k9-felles-integrasjon-pom](https://github.com/navikt/k9-felles)
| `9.2.9` | `9.3.3` |
| [no.nav.k9.felles:k9-felles-db](https://github.com/navikt/k9-felles) |
`9.2.9` | `9.3.3` |
|
[no.nav.k9.felles.integrasjon:k9-sensu-klient](https://github.com/navikt/k9-felles)
| `9.2.9` | `9.3.3` |
|
[no.nav.k9.prosesstask:prosesstask-root](https://github.com/navikt/k9-prosesstask)
| `6.0.4` | `6.0.5` |
| [no.nav.k9:soknad](https://github.com/navikt/k9-format) | `12.7.1` |
`12.7.2` |
| [no.nav.k9:ettersendelse](https://github.com/navikt/k9-format) |
`12.7.1` | `12.7.2` |
| [no.nav.k9:oppgave-ungdomsytelse](https://github.com/navikt/k9-format)
| `12.7.1` | `12.7.2` |


Updates `no.nav.ung.deltakelseopplyser:kontrakt` from 2.7.0 to 2.9.0
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/spring-projects/spring-boot/releases">no.nav.ung.deltakelseopplyser:kontrakt's
releases</a>.</em></p>
<blockquote>
<h2>v2.7.18</h2>
<h2>⚠️ Noteworthy Changes</h2>
<ul>
<li>Following the Paketo team's <a
href="https://blog.paketo.io/posts/paketo-bionic-builder-is-unsafe/">announcement</a>
that the Bionic CNB builders will be removed, the default builder using
by <code>bootBuildImage</code> (Gradle) and
<code>spring-boot:build-image</code> (Maven) has been changed to Paketo
Jammy <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38477">#38477</a></li>
</ul>
<h2>:lady_beetle: Bug Fixes</h2>
<ul>
<li>App fails to start with a NoSuchMethodError when using Flyway 10.0.0
<a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38164">#38164</a></li>
<li>spring.webflux.multipart.max-disk-usage-per-part behaves incorrectly
for values where the number of bytes overflows an int <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38146">#38146</a></li>
<li>Mail health indicator fails when host is not set in properties <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38007">#38007</a></li>
</ul>
<h2>:notebook_with_decorative_cover: Documentation</h2>
<ul>
<li>Document supported SQL comment prefixes <a
href="https://redirect.github.com/spring-projects/spring-boot/pull/38385">#38385</a></li>
<li>Fix link to Elasticsearch health indicator <a
href="https://redirect.github.com/spring-projects/spring-boot/pull/38330">#38330</a></li>
<li>Improve --help and documentation for &quot;encodepassword
-a/--algorithm&quot; in the Spring Boot CLI <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38203">#38203</a></li>
<li>Document that TomcatConnectorCustomizers are not applied to
additional connectors <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38183">#38183</a></li>
<li>MyErrorWebExceptionHandler example in documentation isn't working <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38104">#38104</a></li>
<li>Document that SerializationFeature.WRITE_DURATIONS_AS_TIMESTAMPS is
disabled by default <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38083">#38083</a></li>
<li>Update &quot;Running Behind a Front-end Proxy Server&quot; to
include reactive and ForwardedHeaderTransformer <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/37282">#37282</a></li>
<li>Improve documentation of <code>classpath.idx</code> file and its
generation by the Maven and Gradle plugins <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/37125">#37125</a></li>
<li>Document configuration for building images with Colima <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/34522">#34522</a></li>
<li>Code sample in &quot;Developing Your First Spring Boot
Application&quot; does not work <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/34513">#34513</a></li>
<li>Document ConfigurationPropertyCaching <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/34172">#34172</a></li>
<li>Document that application.* banner variables require a packaged jar
or the use of Boot's launcher <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/33489">#33489</a></li>
<li>Add section on AspectJ support <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/32642">#32642</a></li>
<li>Document server.servlet.encoding.* properties and
server.servlet.encoding.mapping in particular <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/32472">#32472</a></li>
<li>Add a section on customizing embedded reactive servers <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/31917">#31917</a></li>
<li>Clarify that MVC components provided through WebMvcRegistrations are
subject to subsequent processing and configuration by MVC <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/31232">#31232</a></li>
<li>Clarifying documentation on including a top-level
<code>@TestConfiguration</code> class in a test <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/30513">#30513</a></li>
<li>Clarify that <code>@AutoConfigureWebTestClient</code> binds
WebTestClient to mock infrastructure <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/29890">#29890</a></li>
<li>Improve systemd configuration documentation <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/28453">#28453</a></li>
<li>Document how to customize the basePackages that auto-configurations
consider (for example Spring Data Repositories) <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/27549">#27549</a></li>
<li>Document additional user configuration that's required after setting
<code>spring.hateoas.use-hal-as-default-json-media-type</code> to
<code>false</code> <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/26814">#26814</a></li>
<li>Add how-to documentation for test-only database migrations with
Flyway/Liquibase <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/26796">#26796</a></li>
</ul>
<h2>:hammer: Dependency Upgrades</h2>
<ul>
<li>Upgrade to ActiveMQ 5.16.7 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38427">#38427</a></li>
<li>Upgrade to DB2 JDBC 11.5.9.0 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38428">#38428</a></li>
<li>Upgrade to Dropwizard Metrics 4.2.22 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38429">#38429</a></li>
<li>Upgrade to Elasticsearch 7.17.15 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38430">#38430</a></li>
<li>Upgrade to Glassfish JAXB 2.3.9 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38431">#38431</a></li>
<li>Upgrade to Micrometer 1.9.17 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38279">#38279</a></li>
<li>Upgrade to Netty 4.1.101.Final <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38432">#38432</a></li>
<li>Upgrade to Pooled JMS 1.2.6 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38433">#38433</a></li>
<li>Upgrade to Reactor Bom 2020.0.38 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38280">#38280</a></li>
<li>Upgrade to Spring Batch 4.3.10 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38281">#38281</a></li>
<li>Upgrade to Spring Data Bom 2021.2.18 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38282">#38282</a></li>
<li>Upgrade to Spring Framework 5.3.31 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38283">#38283</a></li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li>See full diff in <a
href="https://github.com/spring-projects/spring-boot/commits">compare
view</a></li>
</ul>
</details>
<br />

Updates `no.nav.k9.felles:k9-felles-root` from 9.2.9 to 9.3.3
<details>
<summary>Commits</summary>
<ul>
<li>See full diff in <a
href="https://github.com/navikt/k9-felles/commits">compare view</a></li>
</ul>
</details>
<br />

Updates `no.nav.k9.felles.sikkerhet:k9-felles-sikkerhet` from 9.2.9 to
9.3.3
<details>
<summary>Commits</summary>
<ul>
<li>See full diff in <a
href="https://github.com/navikt/k9-felles/commits">compare view</a></li>
</ul>
</details>
<br />

Updates `no.nav.k9.felles.oidc-token:k9-sikkerhet-azure-cc` from 9.2.9
to 9.3.3
<details>
<summary>Commits</summary>
<ul>
<li>See full diff in <a
href="https://github.com/navikt/k9-felles/commits">compare view</a></li>
</ul>
</details>
<br />

Updates `no.nav.k9.felles.integrasjon:k9-felles-integrasjon-pom` from
9.2.9 to 9.3.3
<details>
<summary>Commits</summary>
<ul>
<li>See full diff in <a
href="https://github.com/navikt/k9-felles/commits">compare view</a></li>
</ul>
</details>
<br />

Updates `no.nav.k9.felles:k9-felles-db` from 9.2.9 to 9.3.3
<details>
<summary>Commits</summary>
<ul>
<li>See full diff in <a
href="https://github.com/navikt/k9-felles/commits">compare view</a></li>
</ul>
</details>
<br />

Updates `no.nav.k9.felles.integrasjon:k9-sensu-klient` from 9.2.9 to
9.3.3
<details>
<summary>Commits</summary>
<ul>
<li>See full diff in <a
href="https://github.com/navikt/k9-felles/commits">compare view</a></li>
</ul>
</details>
<br />

Updates `no.nav.k9.felles.sikkerhet:k9-felles-sikkerhet` from 9.2.9 to
9.3.3
<details>
<summary>Commits</summary>
<ul>
<li>See full diff in <a
href="https://github.com/navikt/k9-felles/commits">compare view</a></li>
</ul>
</details>
<br />

Updates `no.nav.k9.felles.oidc-token:k9-sikkerhet-azure-cc` from 9.2.9
to 9.3.3
<details>
<summary>Commits</summary>
<ul>
<li>See full diff in <a
href="https://github.com/navikt/k9-felles/commits">compare view</a></li>
</ul>
</details>
<br />

Updates `no.nav.k9.felles.integrasjon:k9-felles-integrasjon-pom` from
9.2.9 to 9.3.3
<details>
<summary>Commits</summary>
<ul>
<li>See full diff in <a
href="https://github.com/navikt/k9-felles/commits">compare view</a></li>
</ul>
</details>
<br />

Updates `no.nav.k9.felles:k9-felles-db` from 9.2.9 to 9.3.3
<details>
<summary>Commits</summary>
<ul>
<li>See full diff in <a
href="https://github.com/navikt/k9-felles/commits">compare view</a></li>
</ul>
</details>
<br />

Updates `no.nav.k9.felles.integrasjon:k9-sensu-klient` from 9.2.9 to
9.3.3
<details>
<summary>Commits</summary>
<ul>
<li>See full diff in <a
href="https://github.com/navikt/k9-felles/commits">compare view</a></li>
</ul>
</details>
<br />

Updates `no.nav.k9.prosesstask:prosesstask-root` from 6.0.4 to 6.0.5
<details>
<summary>Commits</summary>
<ul>
<li>See full diff in <a
href="https://github.com/navikt/k9-prosesstask/commits">compare
view</a></li>
</ul>
</details>
<br />

Updates `no.nav.k9:soknad` from 12.7.1 to 12.7.2
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/navikt/k9-format/releases">no.nav.k9:soknad's
releases</a>.</em></p>
<blockquote>
<h2>12.7.2</h2>
<h2>What's Changed</h2>
<h2>🚀 Features</h2>
<ul>
<li>Ny Bekreftelse for generell periodeendring (<a
href="https://redirect.github.com/navikt/k9-format/issues/558">#558</a>)
<a href="https://github.com/EdemEdem"><code>@​EdemEdem</code></a></li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/navikt/k9-format/commit/72342dce1af7bde4a9227c0b0f76e96d3b3d4e93"><code>72342dc</code></a>
Ny Bekreftelse for generell periodeendring (<a
href="https://redirect.github.com/navikt/k9-format/issues/558">#558</a>)</li>
<li>See full diff in <a
href="https://github.com/navikt/k9-format/compare/12.7.1...12.7.2">compare
view</a></li>
</ul>
</details>
<br />

Updates `no.nav.k9:ettersendelse` from 12.7.1 to 12.7.2
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/navikt/k9-format/releases">no.nav.k9:ettersendelse's
releases</a>.</em></p>
<blockquote>
<h2>12.7.2</h2>
<h2>What's Changed</h2>
<h2>🚀 Features</h2>
<ul>
<li>Ny Bekreftelse for generell periodeendring (<a
href="https://redirect.github.com/navikt/k9-format/issues/558">#558</a>)
<a href="https://github.com/EdemEdem"><code>@​EdemEdem</code></a></li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/navikt/k9-format/commit/72342dce1af7bde4a9227c0b0f76e96d3b3d4e93"><code>72342dc</code></a>
Ny Bekreftelse for generell periodeendring (<a
href="https://redirect.github.com/navikt/k9-format/issues/558">#558</a>)</li>
<li>See full diff in <a
href="https://github.com/navikt/k9-format/compare/12.7.1...12.7.2">compare
view</a></li>
</ul>
</details>
<br />

Updates `no.nav.k9:oppgave-ungdomsytelse` from 12.7.1 to 12.7.2
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/navikt/k9-format/releases">no.nav.k9:oppgave-ungdomsytelse's
releases</a>.</em></p>
<blockquote>
<h2>12.7.2</h2>
<h2>What's Changed</h2>
<h2>🚀 Features</h2>
<ul>
<li>Ny Bekreftelse for generell periodeendring (<a
href="https://redirect.github.com/navikt/k9-format/issues/558">#558</a>)
<a href="https://github.com/EdemEdem"><code>@​EdemEdem</code></a></li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/navikt/k9-format/commit/72342dce1af7bde4a9227c0b0f76e96d3b3d4e93"><code>72342dc</code></a>
Ny Bekreftelse for generell periodeendring (<a
href="https://redirect.github.com/navikt/k9-format/issues/558">#558</a>)</li>
<li>See full diff in <a
href="https://github.com/navikt/k9-format/compare/12.7.1...12.7.2">compare
view</a></li>
</ul>
</details>
<br />

Updates `no.nav.k9:ettersendelse` from 12.7.1 to 12.7.2
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/navikt/k9-format/releases">no.nav.k9:ettersendelse's
releases</a>.</em></p>
<blockquote>
<h2>12.7.2</h2>
<h2>What's Changed</h2>
<h2>🚀 Features</h2>
<ul>
<li>Ny Bekreftelse for generell periodeendring (<a
href="https://redirect.github.com/navikt/k9-format/issues/558">#558</a>)
<a href="https://github.com/EdemEdem"><code>@​EdemEdem</code></a></li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/navikt/k9-format/commit/72342dce1af7bde4a9227c0b0f76e96d3b3d4e93"><code>72342dc</code></a>
Ny Bekreftelse for generell periodeendring (<a
href="https://redirect.github.com/navikt/k9-format/issues/558">#558</a>)</li>
<li>See full diff in <a
href="https://github.com/navikt/k9-format/compare/12.7.1...12.7.2">compare
view</a></li>
</ul>
</details>
<br />

Updates `no.nav.k9:oppgave-ungdomsytelse` from 12.7.1 to 12.7.2
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/navikt/k9-format/releases">no.nav.k9:oppgave-ungdomsytelse's
releases</a>.</em></p>
<blockquote>
<h2>12.7.2</h2>
<h2>What's Changed</h2>
<h2>🚀 Features</h2>
<ul>
<li>Ny Bekreftelse for generell periodeendring (<a
href="https://redirect.github.com/navikt/k9-format/issues/558">#558</a>)
<a href="https://github.com/EdemEdem"><code>@​EdemEdem</code></a></li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/navikt/k9-format/commit/72342dce1af7bde4a9227c0b0f76e96d3b3d4e93"><code>72342dc</code></a>
Ny Bekreftelse for generell periodeendring (<a
href="https://redirect.github.com/navikt/k9-format/issues/558">#558</a>)</li>
<li>See full diff in <a
href="https://github.com/navikt/k9-format/compare/12.7.1...12.7.2">compare
view</a></li>
</ul>
</details>
<br />


Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore <dependency name> major version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's major version (unless you unignore this specific
dependency's major version or upgrade to it yourself)
- `@dependabot ignore <dependency name> minor version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's minor version (unless you unignore this specific
dependency's minor version or upgrade to it yourself)
- `@dependabot ignore <dependency name>` will close this group update PR
and stop Dependabot creating any more for the specific dependency
(unless you unignore this specific dependency or upgrade to it yourself)
- `@dependabot unignore <dependency name>` will remove all of the ignore
conditions of the specified dependency
- `@dependabot unignore <dependency name> <ignore condition>` will
remove the ignore condition of the specified dependency and ignore
conditions


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>