Build(deps): Bump jetty.version from 12.1.6 to 12.1.7 (#1172)
Bumps `jetty.version` from 12.1.6 to 12.1.7.
Updates `org.eclipse.jetty:jetty-bom` from 12.1.6 to 12.1.7
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/jetty/jetty.project/releases">org.eclipse.jetty:jetty-bom's
releases</a>.</em></p>
<blockquote>
<h2>12.1.7</h2>
<h1>Special Thanks to the following Eclipse Jetty community members</h1>
<ul>
<li><a href="https://github.com/afarber"><code>@​afarber</code></a>
(Alexander Farber)</li>
</ul>
<h1>Changelog</h1>
<ul>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/14566">#14566</a>
- CompressionHandler/GzipEncoderSink not respect setSyncFlush(true)</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/14495">#14495</a>
- Support Transfer-Encoding chunk extensions</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/14485">#14485</a>
- Illegal header value on UTF-8 encoding when using HTTP/2</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/14442">#14442</a>
- Allow splitting of Transfer-Encoding chunks</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/14436">#14436</a>
- Jetty 12.1.6 HttpFields from(HttpField...) does not provide
opportunity to set compliance listener (<a
href="https://github.com/afarber"><code>@​afarber</code></a>)</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/14435">#14435</a>
- NoSuchMethodError error raised by HttpStateChannel with Jetty 12.1.6
run with maven plugin</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/14408">#14408</a>
- Redundant database index created by JDBCSessionDataStore</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/14373">#14373</a>
- Response listener that avoids any data copies</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/14366">#14366</a>
- Clarify Deprecation Policy</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/14165">#14165</a>
- Integrating Eclipse Soteria with Jetty EE10+</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/jetty/jetty.project/commit/8e2e9db9edceef93d37a63814ed06b921eb7f23d"><code>8e2e9db</code></a>
Updating to version 12.1.7</li>
<li><a
href="https://github.com/jetty/jetty.project/commit/46b1da1ea07d10c34b8814a867ec431955023d1c"><code>46b1da1</code></a>
release check</li>
<li><a
href="https://github.com/jetty/jetty.project/commit/7b41ebd589244ea245bae1262a77a64aee56ab91"><code>7b41ebd</code></a>
release check</li>
<li><a
href="https://github.com/jetty/jetty.project/commit/d596616315cca01780a84703c34186979802f347"><code>d596616</code></a>
dot not needed anymore</li>
<li><a
href="https://github.com/jetty/jetty.project/commit/89802249da77463e64925720d22384034bc5f1a0"><code>8980224</code></a>
fix staging url</li>
<li><a
href="https://github.com/jetty/jetty.project/commit/c7402a13d40b26e9a7f62af86f3de04e85961b6c"><code>c7402a1</code></a>
Fixed missing &quot;requires transitive&quot; in module-info.java
files.</li>
<li><a
href="https://github.com/jetty/jetty.project/commit/fa1f4004bbb8c604730a54065c6ff5579f6f9046"><code>fa1f400</code></a>
Fixes <a
href="https://redirect.github.com/jetty/jetty.project/issues/14366">#14366</a>
- Clarify Deprecation Policy. (<a
href="https://redirect.github.com/jetty/jetty.project/issues/14369">#14369</a>)</li>
<li><a
href="https://github.com/jetty/jetty.project/commit/96d6912a5570a160879e169c3ba3a2d44a065d59"><code>96d6912</code></a>
Fixes <a
href="https://redirect.github.com/jetty/jetty.project/issues/14495">#14495</a>
- Support Transfer-Encoding chunk extensions. (<a
href="https://redirect.github.com/jetty/jetty.project/issues/14496">#14496</a>)</li>
<li><a
href="https://github.com/jetty/jetty.project/commit/10c652ede5ee6362692d09cb1571caa4b3af18d6"><code>10c652e</code></a>
Fixes <a
href="https://redirect.github.com/jetty/jetty.project/issues/14605">#14605</a>
- ServletCoreRequest Read Operations.</li>
<li><a
href="https://github.com/jetty/jetty.project/commit/01de61ac69c064d37ced4c1b45cbc212858df131"><code>01de61a</code></a>
Issue <a
href="https://redirect.github.com/jetty/jetty.project/issues/14566">#14566</a>
- Use GzipEncoderConfig syncFlush in CompressionHandler as well ...</li>
<li>Additional commits viewable in <a
href="https://github.com/jetty/jetty.project/compare/jetty-12.1.6...jetty-12.1.7">compare
view</a></li>
</ul>
</details>
<br />

Updates `org.eclipse.jetty.ee11:jetty-ee11-bom` from 12.1.6 to 12.1.7
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/jetty/jetty.project/releases">org.eclipse.jetty.ee11:jetty-ee11-bom's
releases</a>.</em></p>
<blockquote>
<h2>12.1.7</h2>
<h1>Special Thanks to the following Eclipse Jetty community members</h1>
<ul>
<li><a href="https://github.com/afarber"><code>@​afarber</code></a>
(Alexander Farber)</li>
</ul>
<h1>Changelog</h1>
<ul>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/14566">#14566</a>
- CompressionHandler/GzipEncoderSink not respect setSyncFlush(true)</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/14495">#14495</a>
- Support Transfer-Encoding chunk extensions</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/14485">#14485</a>
- Illegal header value on UTF-8 encoding when using HTTP/2</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/14442">#14442</a>
- Allow splitting of Transfer-Encoding chunks</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/14436">#14436</a>
- Jetty 12.1.6 HttpFields from(HttpField...) does not provide
opportunity to set compliance listener (<a
href="https://github.com/afarber"><code>@​afarber</code></a>)</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/14435">#14435</a>
- NoSuchMethodError error raised by HttpStateChannel with Jetty 12.1.6
run with maven plugin</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/14408">#14408</a>
- Redundant database index created by JDBCSessionDataStore</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/14373">#14373</a>
- Response listener that avoids any data copies</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/14366">#14366</a>
- Clarify Deprecation Policy</li>
<li><a
href="https://redirect.github.com/jetty/jetty.project/issues/14165">#14165</a>
- Integrating Eclipse Soteria with Jetty EE10+</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/jetty/jetty.project/commit/8e2e9db9edceef93d37a63814ed06b921eb7f23d"><code>8e2e9db</code></a>
Updating to version 12.1.7</li>
<li><a
href="https://github.com/jetty/jetty.project/commit/46b1da1ea07d10c34b8814a867ec431955023d1c"><code>46b1da1</code></a>
release check</li>
<li><a
href="https://github.com/jetty/jetty.project/commit/7b41ebd589244ea245bae1262a77a64aee56ab91"><code>7b41ebd</code></a>
release check</li>
<li><a
href="https://github.com/jetty/jetty.project/commit/d596616315cca01780a84703c34186979802f347"><code>d596616</code></a>
dot not needed anymore</li>
<li><a
href="https://github.com/jetty/jetty.project/commit/89802249da77463e64925720d22384034bc5f1a0"><code>8980224</code></a>
fix staging url</li>
<li><a
href="https://github.com/jetty/jetty.project/commit/c7402a13d40b26e9a7f62af86f3de04e85961b6c"><code>c7402a1</code></a>
Fixed missing &quot;requires transitive&quot; in module-info.java
files.</li>
<li><a
href="https://github.com/jetty/jetty.project/commit/fa1f4004bbb8c604730a54065c6ff5579f6f9046"><code>fa1f400</code></a>
Fixes <a
href="https://redirect.github.com/jetty/jetty.project/issues/14366">#14366</a>
- Clarify Deprecation Policy. (<a
href="https://redirect.github.com/jetty/jetty.project/issues/14369">#14369</a>)</li>
<li><a
href="https://github.com/jetty/jetty.project/commit/96d6912a5570a160879e169c3ba3a2d44a065d59"><code>96d6912</code></a>
Fixes <a
href="https://redirect.github.com/jetty/jetty.project/issues/14495">#14495</a>
- Support Transfer-Encoding chunk extensions. (<a
href="https://redirect.github.com/jetty/jetty.project/issues/14496">#14496</a>)</li>
<li><a
href="https://github.com/jetty/jetty.project/commit/10c652ede5ee6362692d09cb1571caa4b3af18d6"><code>10c652e</code></a>
Fixes <a
href="https://redirect.github.com/jetty/jetty.project/issues/14605">#14605</a>
- ServletCoreRequest Read Operations.</li>
<li><a
href="https://github.com/jetty/jetty.project/commit/01de61ac69c064d37ced4c1b45cbc212858df131"><code>01de61a</code></a>
Issue <a
href="https://redirect.github.com/jetty/jetty.project/issues/14566">#14566</a>
- Use GzipEncoderConfig syncFlush in CompressionHandler as well ...</li>
<li>Additional commits viewable in <a
href="https://github.com/jetty/jetty.project/compare/jetty-12.1.6...jetty-12.1.7">compare
view</a></li>
</ul>
</details>
<br />


Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>